name: Trigger auto deployment for testworkflowfilenamesourceco

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/testworkflowfilenamesourceco-AutoDeployTrigger-b340536e-05bb-4899-b4b4-0d30e994a853.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTWORKFLOWFILENAMESOURCECO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTWORKFLOWFILENAMESOURCECO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTWORKFLOWFILENAMESOURCECO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrytnlrvmj27lleo.azurecr.io
          registryUsername: ${{ secrets.TESTWORKFLOWFILENAMESOURCECO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTWORKFLOWFILENAMESOURCECO_REGISTRY_PASSWORD }}
          containerAppName: testworkflowfilenamesourceco
          resourceGroup: qltest
          imageToBuild: containerregistrytnlrvmj27lleo.azurecr.io/testworkflowfilenamesourceco:${{ github.sha }}
          dockerfilePath: Dockerfile


